name: Run Gradle On PRs
on:
  pull_request:
    branches: [main]
jobs:
  gradle:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Clone with specific format
        shell: bash
        run: |
          cd ../
          rm -rf actions-framely-init
          echo "Cloning private repository..."
          # Use a more explicit format for the token
          GH_TOKEN="${{ secrets.PAT_TOKEN }}"
          git clone https://${GH_TOKEN}:x-oauth-basic@github.com/framely/actions-framely-init.git -b v1
          echo "Cloned successfully. Contents:"
          ls -la actions-framely-init
            
      - uses: ./../actions-framely-init
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          feishu-hook-id: ${{ secrets.FEISHU_HOOK_ID }}
          command-main: |-
            if [ -f .ci.sh ]; then bash -xe .ci.sh; fi
          command-post: echo -n post
