name: Run Gradle On PRs
on:
  pull_request:
    branches: [main]
jobs:
  gradle:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Print current directory and GitHub context
        shell: bash
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository: ${{ github.repository }}"
          echo "Running on: ${{ runner.os }}"
      
      - name: Checkout private action directly
        uses: actions/checkout@v3
        with:
          repository: framely/actions-framely-init
          ref: v1
          token: ${{ github.token }}
          path: ./.github/actions/actions-framely-init
      
      - name: Verify private action checkout
        shell: bash
        run: |
          if [ -d "./.github/actions/actions-framely-init" ]; then
            echo "✅ Private action successfully checked out"
            ls -la ./.github/actions/actions-framely-init
          else
            echo "❌ Failed to checkout private action"
            exit 1
          fi
      
      - name: Run framely-init action
        uses: ./.github/actions/actions-framely-init
        with:
          github-token: ${{ github.token }}
          feishu-hook-id: ${{ secrets.FEISHU_HOOK_ID }}
          command-main: |-
            if [ -f .ci.sh ]; then bash -xe .ci.sh; fi
          command-post: echo -n post
